services:
  app_streamlit:
    build:
      context: ./app_streamlit
    depends_on:
      - project-cli
    ports:
      - 8501:8501

  project-cli:
    build:
      context: ./app
    ports:
      - 5000:5000
